# cloudbuild.yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/github.com/aadidevraizada/n8n-cloudrun:$COMMIT_SHA',
        '-f',
        '.devcontainer/Dockerfile',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/github.com/aadidevraizada/n8n-cloudrun:$COMMIT_SHA'

options:
  logging: NONE # or NONE if you want no logs
